<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Notifications\Notifiable;
use Spatie\Translatable\HasTranslations;

class Customer extends Model
{


    use HasTranslations,Notifiable;


    // 3. To define which attributes needs to be translated
    public $translatable =
        ['sender_full_name', 'sender_mother_name',
        'reciver_full_name','reciver_mother_name'];
    protected $fillable = [ 'email','password', 'sender_national_id','sender_phone','address_sender',
     'reciver_national_id','reciver_phone','address_reciver','series_id','number','full_number'];



    public function series(){
        return $this->belongsTo(Series::class,'series_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static ::creating(function ($model){
            $model->number = Customer::where('series_id',$model->series_id)->max('number')+1;
            $model->full_number = $model->series->prefix.'-'.str_pad($model->number,5,'0',STR_PAD_LEFT);

        });
    }
}
